version: "3.7"
services:
  postgres:
    image: postgres:9.6.18
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /data/db/postgres